name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Jalankan workflow setiap kali ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js environment (opsional untuk framework seperti Gatsby/Next.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Instal dependensi dan build situs (sesuaikan dengan kebutuhan framework kamu)
      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      # Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
